
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div style={{width: '100vw', height: '3rem', background: 'var(--background)', position: 'fixed', left: 0, top: 0, zIndex: 999, boxShadow: '3px 3px 5px #00000022',display: 'flex', gap: '2rem', alignItems: 'center', justifyContent: 'space-between'}}>
          <div style={{display: 'flex', gap: '2rem', marginLeft: '2rem'}}>
            <div><b><span>PeachtArt</span></b></div>
            <div>라이브</div>
            <div>영상</div>
          </div>
          <div style={{display: 'flex', gap: '2rem', marginRight: '2rem'}}>
            <div>마이페이지</div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
